apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-latency-fault
spec:
  hosts:
    - my-app-service
  http:
    - fault:
        delay:
          percentage:
            value: 100.0
          fixedDelay: 5s # Every request will now take 5 seconds
      route:
        - destination:
            host: my-app-service
